version: '2.1'

services:
  edge: # front end
    build:
      context: .
    volumes:
      - "./edge.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./nott.html:/usr/local/openresty/nginx/index.html"
      - "./src/:/lua/src/"
    depends_on:
      - ingest
      - redis_cluster
    links:
      - ingest
      - redis_cluster
    ports:
      - "8080:8080"

  ingest: # back end
    build:
      context: .
      dockerfile: Dockerfile.ingest
    volumes:
      - "./ingest.conf:/config/nginx.conf"
    ports:
      - "1935:1935"

  redis_cluster: # data store
    image: grokzen/redis-cluster:latest
    ports:
      - '7000-7005:7000-7005'
  test:
    command: busted -v --shuffle
    environment:
      - TRAVIS=true
      - CI=true
      - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
      - TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
      - TRAVIS_BRANCH=${TRAVIS_BRANCH}
      - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ".:/lua/"
    working_dir: "/lua"

  lint:
    command: bash -c "luacheck -q ."
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ".:/lua/"
    working_dir: "/lua"

